### ISSUE TITLE
add method to cancel the training

### ISSUE THREAD

**Issue by JulesFrancoise** [Ircam-RnD/xmm-node#3]
It would be very useful to have the possibility to cancel the training process (as in xmm). Do you know if there is any way to cancel the webworker without risk?

**Comment by josephlarralde** [comment]
I'll be working on it. I think so ...

**Comment by josephlarralde** [comment]
Just got it working, you can check the develop branch.
I can't swear it's without risk ... I'm using xmm::MultithreadingMode::Background in the asyncworker, and I read somewhere that using threads is not recommended when writing node addons.
But, with the dumb test ('npm run tests') it works fine.
More testing / discussing needed ...

**Comment by josephlarralde** [comment]
From this reference : https://blog.scottfrees.com/how-not-to-access-node-js-from-c-worker-threads , using threads like this doesn't sound so dangerous, as there is no concurrent access from the main event loop.
So it seems to be safe to cancel the training this way.
If you see no other potential issues, I think I'll merge to the master branch soon.

**Comment by JulesFrancoise** [comment]
Hi Joseph,

Awesome, great work!
The training should be thread-safe with the XMM API. Do you use the cancelTraining method? It should make sure that you don't leave the object in an undefined state.
I will give it a try soon, and I will let you know!

**Comment by josephlarralde** [comment]
Thanks !

Yes, I use the cancelTraining method from xmmModel.
I think I misunderstood the article I reference above when I first read it some time ago, that's why I was creating the wrapped xmmModel with multithreading = parallel by default, to avoid any potential conflict between XMM's threads and Node's threading system, but that was a bit too cautious ...

Let me know if it works on your side and I'll do the merge.
Cheers

**Comment by josephlarralde** [comment]
Finally, as I saw no obvious reason why it would crash, I merged into master and added a warning note to the documentation.
